import {House,Info,LayoutGrid,MapPin,Heart,CirclePlus,Share2,Search,ChevronLeft,ChevronRight} from "lucide-react";
type S={size?:number};
export const HomeI=({size=20}:S)=><House size={size} aria-hidden="true"/>;
export const InfoI=({size=20}:S)=><Info size={size} aria-hidden="true"/>;
export const GridI=({size=20}:S)=><LayoutGrid size={size} aria-hidden="true"/>;
export const PinI=({size=20}:S)=><MapPin size={size} aria-hidden="true"/>;
export const HeartI=({size=20}:S)=><Heart size={size} aria-hidden="true"/>;
export const PlusI=({size=20}:S)=><CirclePlus size={size} aria-hidden="true"/>;
export const ShareI=({size=20}:S)=><Share2 size={size} aria-hidden="true"/>;
export const SearchI=({size=20}:S)=><Search size={size} aria-hidden="true"/>;
export const PrevI=({size=20}:S)=><ChevronLeft size={size} aria-hidden="true"/>;
export const NextI=({size=20}:S)=><ChevronRight size={size} aria-hidden="true"/>;